### PR TITLE
Feature/seo tab extension

### PR DESCRIPTION
**Pull request by gor0utine**

### CODE REVIEW

**Comment by danrot** [comment]
Is it possible that you have an error in the poedit-configuration? If you look at the zoolu-de.po file, you can see that many translations have been deleted, which should not be the case.

And I hope I will be able to test your pull request in detail today.

**Comment by danrot** [comment]
I had the same problem with the po-files, you have to configure poedit to find *.phtml files also. You can do this under settings -> parser -> PHP.

**Comment by gor0utine** [comment]
i'll fix.

**Comment by danrot** [comment]
Don't you have already solved the translation problem? Poedit should get the deleted changes back automatically.

**Comment by gor0utine** [comment]
fixed

**Comment by gor0utine** [comment]
please run sql queries

<pre>
UPDATE `fields` SET `validators` = '' WHERE `name` ='seo_keywords';
UPDATE `fields` SET `validators` = '' WHERE `name` ='seo_keywords';
</pre>

**Comment by danrot** [comment]
I assume you also have these changes in your sql scripts? For the last test I will create a new installation and database anyway. Hope that I manage it this week...

**Comment by gor0utine** [comment]
Yes, sorry.

I thought that we need check keywords limit with PHP too.

But when you told me about coloring with red keywords count, I removed checking limits.

**Comment by danrot** [comment]
I have found the mistake, causing the deletion of the new files. In the following commit you have made a merge, without having the new files included: https://github.com/NurbekChymbaev/ZOOLU/commit/75326832600d0034138ec7bc15000d4cfcd50d3d

You can see this in the network graph here on github. Can you try to delete this commit, and make the changes another time?

**Comment by gor0utine** [comment]
Hi, Daniel
I have a problem with commit removals.
Can we solve them together, when you have time ?

**Comment by danrot** [comment]
Sure, I will write you as soon as I have time. And one question, how did you successfully remove the last two commits?

**Comment by gor0utine** [comment]
I can't remember git command, that found in Internet.

something like this

git push -f origin HEAD^:master
git rebase -i HEAD~2

The last commits was easy to remove, but remove a certain commit is not 
easy.

On 20.11.12 13:24, Daniel Rotter wrote:

> Sure, I will write you as soon as I have time. And one question, how 
> did you successfully remove the last two commits?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/massiveart-webservices/ZOOLU/pull/7#issuecomment-10544965. 

## 

Nurbek Chymbaev, PHP Developer
skype: nurbek188 | chat: nurbek188@gmail.com

**Comment by danrot** [comment]
You should also be able to use an interactive rebase (git rebase -i), there is a good tutorial: http://christoph.ruegg.name/blog/2010/5/5/git-howto-revert-a-commit-already-pushed-to-a-remote-reposit.html

You should read the heading "Case 2: Delete the second last commit", and take these steps for https://github.com/NurbekChymbaev/ZOOLU/commit/75326832600d0034138ec7bc15000d4cfcd50d3d

Of course you need to make the really desired changes (editing the character count) afterwards in a new commit.

**Pull request closed without merging**
